### ISSUE TITLE
There's not a lot of functionality

### ISSUE THREAD

**Issue by Razpudding** [nickrttn/real-time-web#1]
The code is very neat and quite modern, but there's not a lot of custom functionality yet. what did you experiment with this week/ what did you try to learn?

**Comment by nickrttn** [comment]
It's a simple example, agreed. I did try to implement WebSockets without any library. However, there's not a lot to be found on exactly how to do that, and the process frustrated me. So I deleted the code and made it work with `socket.io`. Even though I learned some stuff about the `net` and `http` Node.js libraries, as well as the browsers' `WebSocket` I've got nothing to show for it.

**Comment by nickrttn** [comment]
I should have saved my experiments in another branch, I am well aware.

**Comment by Razpudding** [comment]
I agree with your response. Since it makes more sense to build a new project this week, I'll close this issue.
